### ISSUE TITLE
inserire widget twitter #iovotoopendata

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/facciamopolitica#5]
Questo il codice

```
<a class="twitter-timeline" href="https://twitter.com/hashtag/iovotoopendata" data-widget-id="599923097358180352">Tweet riguardo #iovotoopendata</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
```

**Comment by nelsonmau** [comment]
Hashtag farei #iovotopendata
Una sola "o"

**Comment by aborruso** [comment]
On 17 May 2015 at 15:11, Andrea Nelson Mauro notifications@github.com
wrote:

> Hashtag farei #iovotopendata
> Una sola "o"

Nelson è corretto. Forse è meglio cambiare anche il dominio di terzo
livello.

Lo proponi tu per favore in lista (#nosocial)?

## 

Andrea Borruso
website: http://blog.spaziogis.it
GEO+ geomatica in Italia http://bit.ly/GEOplus  http://bit.ly/GEOplus

## 38° 7' 48" N, 13° 21' 9" E, EPSG:4326

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by aborruso** [comment]
Ho inserito nel search sia #iovotoopendata  che #iovotopendata
