### ISSUE TITLE
Tremestieri dovrebbe essere etneo

### ISSUE THREAD

**Issue by cristianolongo** [SiciliaHub/facciamopolitica#7]
Selezionando Catania nella mappa compare il comune di Tremestieri in provincia di messina, mentre invece si tratta del comune di Tremestieri Etneo.

**Comment by nelsonmau** [comment]
Confermo. Tremestieri di messina è solo una frazione del comune fi messina,
non fa comune autonomo

**Comment by aborruso** [comment]
2015-05-17 19:30 GMT+02:00 Andrea Nelson Mauro notifications@github.com:

> Confermo. Tremestieri di messina è solo una frazione del comune fi messina,
> non fa comune autonomo

Se si corregge il toponimo nel foglio elettronico, dovrebbe ripartire il
geocoding automatico; si possono mettere in ogni caso "a mano" le
coordinate :)

## 

Andrea Borruso
website: http://blog.spaziogis.it
GEO+ geomatica in Italia http://bit.ly/GEOplus  http://bit.ly/GEOplus

## 38° 7' 48" N, 13° 21' 9" E, EPSG:4326

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino
