### ISSUE TITLE
Preparare immagine per opengraph

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/facciamopolitica#9]
Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images.

**Comment by nelsonmau** [comment]
@aborruso take a look here!
![iovotopendata_1200x630](https://cloud.githubusercontent.com/assets/1769578/7675587/6c0288fe-fd3a-11e4-81a4-fd5046eb75e6.png)

**Comment by aborruso** [comment]
Great!

Invii pure per favore il file "nativo"?

On 18 May 2015 at 08:46, Andrea Nelson Mauro notifications@github.com
wrote:

> @aborruso https://github.com/aborruso take a look here!
> [image: iovotopendata_1200x630]
> https://cloud.githubusercontent.com/assets/1769578/7675571/4db6380a-fd3a-11e4-8184-62c4bfe2a418.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SiciliaHub/facciamopolitica/issues/9#issuecomment-102938319
> .

## 

Andrea Borruso
website: http://blog.spaziogis.it
GEO+ geomatica in Italia http://bit.ly/GEOplus  http://bit.ly/GEOplus

## 38° 7' 48" N, 13° 21' 9" E, EPSG:4326

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino
